name: Workflow2

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed


jobs:
  publish-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Test input
    runs-on: ubuntu-latest
    steps:
      - name: Echo debug
        uses: actions/github-script@v7
        with:
          script: |
            const workflow_run = JSON.stringify(context.payload.workflow_run)
            const payload = JSON.stringify(context.payload)
        
            console.log(payload)
            console.log(workflow_run)


