name: Workflow1

on:
  workflow_dispatch:
  # push:
  #   branches: [master]

jobs:
  test:
    name: Test sharing artifact
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: |
          touch releaseTagVersion.txt
          echo "test1" > releaseTagVersion.txt
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: releaseTagVersion.txt



